import React from "react";
import { useNavigate, useLocation } from "react-router-dom";
import { MdArrowBack, MdStar, MdShare, MdDownload } from "react-icons/md";

export default function FeedbackPage() {
  const navigate = useNavigate();
  const location = useLocation();
  const feedback = location.state?.feedback || "No feedback available.";

  const downloadFeedback = () => {
    const element = document.createElement("a");
    const file = new Blob([feedback], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = "session-feedback.txt";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="min-h-screen gradient-bg py-8 px-4">
      <div className="max-w-4xl mx-auto">
        <button
          onClick={() => navigate("/")}
          className="flex items-center gap-2 text-gray-600 hover:text-gray-900 mb-8 transition-colors"
        >
          <MdArrowBack />
          Back to Home
        </button>

        <div className="card overflow-hidden">
          <div className="bg-gradient-to-r from-indigo-600 to-purple-600 p-8 text-white">
            <div className="flex items-center justify-between">
              <div>
                <h1 className="text-3xl font-bold mb-2">Session Feedback</h1>
                <p className="text-indigo-100">Your personalized AI-generated feedback</p>
              </div>
              <div className="hidden md:flex items-center gap-2">
                {[...Array(5)].map((_, i) => (
                  <MdStar key={i} className="text-yellow-300 text-xl" />
                ))}
              </div>
            </div>
          </div>

          <div className="p-8">
            <div className="prose prose-lg max-w-none">
              <div className="bg-gradient-to-br from-gray-50 to-white p-6 rounded-2xl border border-gray-200">
                <div className="flex items-center gap-3 mb-6">
                  <div className="w-12 h-12 rounded-full bg-gradient-to-r from-indigo-100 to-purple-100 flex items-center justify-center">
                    <MdStar className="text-2xl text-indigo-600" />
                  </div>
                  <div>
                    <h2 className="text-xl font-bold text-gray-900">AI Assessment</h2>
                    <p className="text-gray-600">Generated by LLM Moderator</p>
                  </div>
                </div>
                
                <div className="space-y-4">
                  {feedback.split('\n').map((paragraph, index) => (
                    paragraph.trim() && (
                      <p key={index} className="text-gray-700 leading-relaxed">
                        {paragraph}
                      </p>
                    )
                  ))}
                </div>
              </div>
            </div>

            {/* Action Buttons */}
            <div className="mt-8 pt-8 border-t border-gray-200">
              <div className="flex flex-col sm:flex-row gap-4">
                <button
                  onClick={() => navigate("/")}
                  className="btn-primary flex-1 py-3 flex items-center justify-center gap-2"
                >
                  <MdArrowBack />
                  Return to Dashboard
                </button>
                <button
                  onClick={downloadFeedback}
                  className="flex-1 bg-gradient-to-r from-gray-600 to-gray-700 text-white py-3 rounded-xl font-medium hover:from-gray-700 hover:to-gray-800 transition-all duration-200 flex items-center justify-center gap-2"
                >
                  <MdDownload />
                  Download Feedback
                </button>
                <button
                  onClick={() => {
                    if (navigator.share) {
                      navigator.share({
                        title: 'My Session Feedback',
                        text: feedback.substring(0, 100) + '...',
                      });
                    } else {
                      navigator.clipboard.writeText(feedback);
                      alert('Feedback copied to clipboard!');
                    }
                  }}
                  className="flex-1 bg-gradient-to-r from-green-600 to-green-700 text-white py-3 rounded-xl font-medium hover:from-green-700 hover:to-green-800 transition-all duration-200 flex items-center justify-center gap-2"
                >
                  <MdShare />
                  Share Feedback
                </button>
              </div>
            </div>

            {/* Stats Cards */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-8">
              <div className="bg-gradient-to-br from-blue-50 to-blue-100 p-4 rounded-2xl">
                <h4 className="font-semibold text-blue-900 mb-2">Session Length</h4>
                <p className="text-2xl font-bold text-blue-700">15 mins</p>
              </div>
              <div className="bg-gradient-to-br from-green-50 to-green-100 p-4 rounded-2xl">
                <h4 className="font-semibold text-green-900 mb-2">Messages Sent</h4>
                <p className="text-2xl font-bold text-green-700">24</p>
              </div>
              <div className="bg-gradient-to-br from-purple-50 to-purple-100 p-4 rounded-2xl">
                <h4 className="font-semibold text-purple-900 mb-2">Engagement Score</h4>
                <p className="text-2xl font-bold text-purple-700">8.5/10</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}